### ISSUE TITLE
Ask for merge and release permissions

### ISSUE THREAD

**Issue by ares** [fog/fog-libvirt#118] opened 2022-06-15 12:08 UTC
A set of issues was reported on Foreman project with recent version of libvirt. Some have even fixing PRs here, e.g. https://github.com/fog/fog-libvirt/pull/116

I know this gem was maintained more actively, but I suppose it falls under similar category as other adapters, @geemus if you wouldn't object, we'd like to get merge permissions and release ownership on rubygems so we could restore the compatibility with the new version of libvirt. That means, we would not actively develop the gem, but we'd try to maintain it, since it's Foreman project dependency. 

Thanks for considering.

**Comment by geemus** [comment] 2022-06-17 20:56
Yes, I think that sounds reasonable. I think I just need your Rubygems associated email addresses.

Could share them with me by email (it's my username  at gmail) so you all don't have to post them here?

Thanks.

**Comment by ekohl** [comment] 2022-06-20 12:15
I've sent you an email, also with the request to add https://rubygems.org/profiles/theforeman so the Foreman project admins have a fallback. Relying on individuals can be tricky. The only downside is that that account has no 2FA.

**Comment by geemus** [comment] 2022-06-21 02:12
@ekohl Great, thanks. I've invited both as owners, so I think they should work once confirmed.

**Comment by ekohl** [comment] 2022-06-21 08:41
I see both icons on https://rubygems.org/gems/fog-libvirt so I think we can close this out. Thanks!

**Closed by ekohl** 2022-06-21 08:41 UTC

**Comment by ares** [comment] 2022-06-21 10:07
Thank you @geemus!

**Comment by electrofelix** [comment] 2022-11-30 23:57
@ekohl does this mean a new release will be forthcoming? There is a fix merged since the last release that would be nice to see in a release as it will fix the destroy behaviour when nvram is enabled for vagrant-libvirt https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1371

**Comment by ekohl** [comment] 2022-12-01 16:14
I released all open changes since 0.9.0 and released 0.10.0: https://rubygems.org/gems/fog-libvirt/versions/0.10.0
